Important questions:
1. Reverse Linked list inplace- (Kunal Kuswaha video 45) - Very Important
2. Inplace reversal of linklist.
3. Fast and slow pointer.

 middle => 3 val: 4  val: 3  dummyhead => 1 reverse => 4 dummyhead => 2 reverse => 3
